import { useState } from 'react'
import { genreClass, type Book } from '../data/books'
import { dateKey, formatDate } from '../lib/date'
import { genreLabel, type Language } from '../i18n'
import { pluralizePl } from '../lib/plural'

type CalendarProps={year:number;month:number;books:Book[];onOpen:(book:Book)=>void;language:Language}
function CalendarEvent({book,onOpen,language}:{book:Book;onOpen:(book:Book)=>void;language:Language}){const en=language==='en';return <button className={`calendar-event ${genreClass(book.genre)}`} type="button" onClick={()=>onOpen(book)} aria-label={en?`${book.title}, ${book.author}. Open details`:`${book.title}, ${book.author}. Otwórz szczegóły książki`}><span className="event-title">{book.title}</span><span className="event-tooltip" aria-hidden="true"><img src={book.cover} alt=""/><span className="event-tooltip-copy"><strong>{book.title}</strong><span>{book.author}</span><span>{book.publisher}</span><span>{genreLabel(book.genre,language)} · {formatDate(book.releaseDate,language)}</span><em>{en?'Click for details':'Kliknij, aby zobaczyć więcej'}</em></span></span></button>}
function CalendarDay({day,year,month,books,onOpen,column,language}:{day:number;year:number;month:number;books:Book[];onOpen:(book:Book)=>void;column:number;language:Language}){const en=language==='en';const iso=dateKey(new Date(year,month,day));const today=dateKey(new Date());const dayBooks=books.filter(book=>book.releaseDate===iso);const [showAll,setShowAll]=useState(false);const visibleBooks=showAll?dayBooks:dayBooks.slice(0,3);const releaseWord=en?(dayBooks.length===1?'release':'releases'):pluralizePl(dayBooks.length,'premiera','premiery','premier');return <div className={`calendar-day ${column>=5?'weekend':''} ${iso===today?'today':''} ${iso<today?'past':''} ${dayBooks.length?`has-events ${genreClass(dayBooks[0].genre)}`:''}`} role="gridcell" aria-label={en?`Day ${day}, ${dayBooks.length} ${releaseWord}`:`${day}. dzień miesiąca, ${dayBooks.length} ${releaseWord}`}><span className="day-number">{day}{iso===today&&<i>{en?'today':'dziś'}</i>}</span><div className="day-books">{visibleBooks.map(book=><CalendarEvent key={book.id} book={book} onOpen={onOpen} language={language}/>)}{dayBooks.length>3&&<button className="day-more" type="button" aria-expanded={showAll} onClick={()=>setShowAll(value=>!value)}>{showAll?(en?'Show less':'Pokaż mniej'):`+ ${dayBooks.length-3} ${en?'more':'więcej'}`}</button>}</div></div>}
export function Calendar({year,month,books,onOpen,language}:CalendarProps){const first=(new Date(year,month,1).getDay()+6)%7;const days=new Date(year,month+1,0).getDate();const cells=Array.from({length:Math.ceil((first+days)/7)*7},(_,i)=>i-first+1);const weekdays=language==='en'?['Mon','Tue','Wed','Thu','Fri','Sat','Sun']:['Pon','Wt','Śr','Czw','Pt','Sob','Niedz'];return <div className="calendar-wrap"><div className="calendar" role="grid" aria-label={language==='en'?`Release calendar for ${month+1}/${year}`:`Kalendarz premier na ${month+1}.${year}`}><div className="calendar-weekdays" role="row">{weekdays.map(day=><div role="columnheader" key={day}>{day}</div>)}</div><div className="calendar-cells">{cells.map((day,i)=>day<1||day>days?<div className="calendar-day outside" key={i} aria-hidden="true"/>:<CalendarDay key={`${year}-${month}-${day}`} day={day} year={year} month={month} books={books} onOpen={onOpen} column={i%7} language={language}/>)}</div></div></div>}
