import { Search, SlidersHorizontal, X } from 'lucide-react'
import { genreClass, genres, type Genre } from '../data/books'
import { genreLabel, type Language } from '../i18n'
import { pluralizePl } from '../lib/plural'
export type TimeRange = 'all'|'today'|'week'|'month'
export type FiltersState = { query:string; publishers:string[]; genres:Genre[]; range:TimeRange; favoritesOnly:boolean }
export function SearchBox({value,onChange,resultCount,language}:{value:string;onChange:(v:string)=>void;resultCount:number;language:Language}) {const en=language==='en';return <div className="search-block"><label className="search-box"><Search size={19}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={en?'Search by title, author, or publisher…':'Szukaj książki, autora lub wydawnictwa…'} aria-label={en?'Search by title, author, or publisher':'Szukaj książki, autora lub wydawnictwa'}/>{value&&<button onClick={()=>onChange('')} aria-label={en?'Clear search':'Wyczyść wyszukiwanie'}><X size={17}/></button>}</label>{value&&<p className="search-count" aria-live="polite">{en?`${resultCount} ${resultCount===1?'result':'results'}`:`Znaleziono ${resultCount} ${pluralizePl(resultCount,'wynik','wyniki','wyników')}`}</p>}</div>}
export function Filters({filters,onChange,onClear,open,onClose,publishers,language}:{filters:FiltersState;onChange:(v:FiltersState)=>void;onClear:()=>void;open:boolean;onClose:()=>void;publishers:string[];language:Language}) {const en=language==='en';const toggle=<T,>(items:T[],item:T)=>items.includes(item)?items.filter(v=>v!==item):[...items,item];const ranges:[TimeRange,string][]=en?[['all','All releases'],['today','Today'],['week','Next 7 days'],['month','Next 30 days']]:[['all','Wszystkie premiery'],['today','Dzisiaj'],['week','Najbliższe 7 dni'],['month','Najbliższe 30 dni']];return <><button className="mobile-filter-button" onClick={onClose}><SlidersHorizontal size={17}/> {en?'Filters':'Filtry'} <span>{filters.publishers.length+filters.genres.length+(filters.range!=='all'?1:0)+(filters.favoritesOnly?1:0)}</span></button>{open&&<button className="filter-backdrop" onClick={onClose} aria-label={en?'Close filters':'Zamknij filtry'}/>}<aside className={`filters-panel ${open?'open':''}`} aria-label={en?'Release filters':'Filtry premier'}><div className="filters-top"><h3>{en?'Filters':'Filtry'} <SlidersHorizontal size={17}/></h3><button onClick={onClear}>{en?'Clear filters':'Wyczyść filtry'}</button><button className="filter-close" onClick={onClose} aria-label={en?'Close filters':'Zamknij filtry'}><X/></button></div><fieldset><legend>{en?'Time range':'Zakres czasu'}</legend><div className="radio-stack">{ranges.map(([value,label])=><label key={value}><input type="radio" name="range" checked={filters.range===value} onChange={()=>onChange({...filters,range:value})}/><span>{label}</span></label>)}</div></fieldset><fieldset><legend>{en?'Genre':'Gatunek'}</legend><div className="check-stack genre-filters">{genres.map(genre=><label className={genreClass(genre)} key={genre}><input type="checkbox" checked={filters.genres.includes(genre)} onChange={()=>onChange({...filters,genres:toggle(filters.genres,genre)})}/><i aria-hidden="true"/><span>{genreLabel(genre,language)}</span></label>)}</div></fieldset><fieldset><legend>{en?'Publisher':'Wydawnictwo'}</legend><div className="check-stack publishers-stack">{publishers.map(publisher=><label key={publisher}><input type="checkbox" checked={filters.publishers.includes(publisher)} onChange={()=>onChange({...filters,publishers:toggle(filters.publishers,publisher)})}/><span>{publisher}</span></label>)}</div></fieldset><button className="apply-filters" onClick={onClose}>{en?'Show releases':'Pokaż premiery'}</button></aside></>}
export function FilterChips({filters,onChange,onClear,language}:{filters:FiltersState;onChange:(v:FiltersState)=>void;onClear:()=>void;language:Language}) {const en=language==='en';const chips=[...filters.genres.map(value=>({key:`g-${value}`,label:genreLabel(value,language),className:genreClass(value),remove:()=>onChange({...filters,genres:filters.genres.filter(g=>g!==value)})})),...filters.publishers.map(value=>({key:`p-${value}`,label:value,className:'',remove:()=>onChange({...filters,publishers:filters.publishers.filter(p=>p!==value)})})),...(filters.range!=='all'?[{key:'range',label:({today:en?'Today':'Dzisiaj',week:en?'7 days':'7 dni',month:en?'30 days':'30 dni'} as Record<string,string>)[filters.range],className:'',remove:()=>onChange({...filters,range:'all'})}]:[]),...(filters.favoritesOnly?[{key:'fav',label:en?'Favorites':'Ulubione',className:'',remove:()=>onChange({...filters,favoritesOnly:false})}]:[])];return chips.length>0?<div className="chips" aria-label={en?'Active filters':'Aktywne filtry'}>{chips.map(chip=><button className={chip.className} key={chip.key} onClick={chip.remove}>{chip.label}<X size={13}/></button>)}<button className="clear-chip" onClick={onClear}>{en?'Clear all':'Wyczyść wszystko'}</button></div>:null}
